/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics.of.software.architecture;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
